# All your application-wide configuration should live here.
# Every parameter here will be automatically transformed into
# an "app.%s" parameter inside the service container.

all:
    name_pattern: <em>%s</em>

dev:  ~
test: ~
prod: ~
