# assetic is an asset manager for your application
# docs: http://bit.ly/assetic-doc
# config: http://bit.ly/assetic-ref

all:
    read_from:      %kernel.web_dir%
    use_controller: false

    # use kernel.yml to configure this parameters
    java: %bin_java%
    node: %bin_node%
    ruby: %bin_ruby%
    sass: %bin_sass%

    # enable filters for your project
    filters:
        # this filter rewrites urls inside your css files
        # to match project structure. you might want to use
        # it in dev environment, where use_controller is
        # enabled
        cssrewrite: ~

        # http://yhoo.it/yui-compressor
        yui_css: { jar: %jar_yui% }

        # http://lesscss.org/
        less: ~

        # http://sass-lang.com/
        scss: ~
        sass: ~

        # http://coffeescript.org/
        coffee: { bin: %bin_coffee% }

dev:
    # This tells Symfony to process your assets through a control
    # in the this environment. This is the easiest setting, but see http://bit.ly/assetic-controllers
    # if you think your pages are loading slowly while developing.
    use_controller: true
test:
    use_controller: true
