all:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

prod:
    orm:
        metadata_cache_driver:  apc
        result_cache_driver:    apc
        query_cache_driver:     apc
