# doctrine provides M for your VC
# docs: http://bit.ly/doctrine2-docs
# config: http://bit.ly/doctrine2-ref

all:
    # DBAL connection
    # see: http://bit.ly/doctrine2-multiple-em
    #
    dbal:
        # if more than one connection is used, name them
        #   api:
        #       accessed by service name [doctrine.dbal.api_connection]
        #       driver: %api_database_driver%
        #       host:   %api_database_host%
        #       ...
        #
        #   read_only:
        #       ...
        #
        # if no named connections provided - configuration below
        # would be assigned to "default" connection

        # use config/kernel.yml to configure this parameters:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        # if more than one entity manager is used
        # see: http://bit.ly/doctrine2-multiple-em
        # api:
        #     accessed by service name [doctrine.orm.api_entity_manager]
        #     connection: api

test:
    dbal:
        # use config/kernel.yml to configure database name.
        # in test environment, _test suffix will be assigned to
        # it automatically
        dbname: %database_name%_test

prod:
    orm:
        # use apc for caching in production
        metadata_cache_driver: apc
        result_cache_driver:   apc
        query_cache_driver:    apc
