# main Symfony2 configuration section
# docs: http://symfony.com/
# config: http://bit.ly/framework-ref

all:
    # turn on Edge Side Includes if you want to cache
    # small blocks of content on your pages separately
    # about ESI: http://bit.ly/esi-wiki
    # docs: http://bit.ly/sf2-cache
    # esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    # see: http://bit.ly/sf2-templating-ref
    templating:
        engines: ['twig']
        # assets_version: v2
        # assets_base_urls:
        #    - //somecdn.com/
    session:
        default_locale: %locale%
        auto_start:     true

    profiler: { only_exceptions: false }

    # Makes exceptions auto-link to your editor: http://bit.ly/sf2-ide
    # ide: textmate # could alsobe "macvim" or custom "txmt://open?url=file://%%f&line=%%l"

prod:
    router: { resource: "%kernel.config_dir%/routing/prod.yml" }

dev:
    router: { resource: "%kernel.config_dir%/routing/dev.yml" }

test:
    router:  { resource: "%kernel.config_dir%/routing/test.yml" }
    test:    ~
    session: { storage_id: session.storage.filesystem }
