all:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: fr #%locale%
        auto_start:     true

    profiler: { only_exceptions: false }

prod:
    router:   { resource: "%kernel.config_dir%/routing/prod.yml" }

dev:
    router:   { resource: "%kernel.config_dir%/routing/dev.yml" }

test:
    router:   { resource: "%kernel.config_dir%/routing/test.yml" }
    test: ~
    session:
        storage_id: session.storage.filesystem
