all:
    application_routing:   true
    application_views:     true
    application_structure: true
    assetic_pipeline:
        enabled:  true
        paths:
            - %kernel.project_dir%/public
            - %kernel.root_dir%/vendor/assets
