# monolog is logging layer of your application
# docs: http://bit.ly/monolog-doc
# config: http://bit.ly/monolog-ref

prod:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

dev:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        # http://www.firephp.org/
        firephp:
            type:  firephp
            level: info
