# swiftmailer is the mailing servicefor your application
# docs: http://bit.ly/swiftmailer-doc
# config: http://bit.ly/swiftmailer-ref

all:
    # use kernel.yml to configure this parameters
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    # sender_address: info@yourdomain.com

dev:
    # If you want *all* mails to be sent to a single address (instead
    # of the actual recipient) while developing, use this.
    # delivery_address: yourname@gmail.com

test:
    disable_delivery: true
