all:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/routing/all.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

dev:
    router:   { resource: "%kernel.root_dir%/routing/dev.yml" }
    profiler: { only_exceptions: false }

test:
    router:   { resource: "%kernel.root_dir%/routing/dev.yml" }
    profiler: { only_exceptions: false }
    test: ~
    session:
        storage_id: session.storage.filesystem
