# This is the namespace of your "application" bundle in the src/ directory
# For example, if this is "KnpRad", then you will have a "src/KnpRad/" directory
project: KnpRad

all:
    bundles:
        - Symfony\Bundle\FrameworkBundle\FrameworkBundle
        - Symfony\Bundle\SecurityBundle\SecurityBundle
        - Symfony\Bundle\TwigBundle\TwigBundle
        - Symfony\Bundle\MonologBundle\MonologBundle
        - Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle
        - Symfony\Bundle\AsseticBundle\AsseticBundle
        - Symfony\Bundle\DoctrineBundle\DoctrineBundle
        - Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle

    # Parameters are like variables that can be references later in any
    # configuration file as: %locale%.
    # See: http://bit.ly/sf2-parameter
    parameters:
        locale:            en
        secret:            ThisTokenIsNotSoSecretChangeIt

        database_driver:   pdo_mysql
        database_host:     localhost
        database_port:     ~
        database_name:     symfony
        database_user:     root
        database_password: ~

        mailer_transport:  smtp
        mailer_host:       localhost
        mailer_user:       ~
        mailer_password:   ~

        bin_java:          /usr/bin/java
        bin_node:          /usr/bin/node
        bin_ruby:          /usr/bin/ruby
        bin_sass:          /usr/bin/sass
        bin_coffee:        /usr/bin/coffee
        jar_yui:           %kernel.root_dir%/vendor/yuicompressor.jar

dev:
    bundles:
        - Symfony\Bundle\WebProfilerBundle\WebProfilerBundle

test:
    bundles:
        - Symfony\Bundle\WebProfilerBundle\WebProfilerBundle
