Author:
    fields:
        first_name: string(100)
        last_name:  string(100)
        biography:  { type: text, notnull: false }

Post:
    fields:
        author: manyToOne(Author)
        title:  ~
        body:   text
        tags:   manyToMany(Tag)

Tag:
    fields:
        name:   { unique: true }
        posts:  manyToOne(Post)
